config/routes.rb
Rails.application.routes.draw do
	resources :games do
		get "delete"
	end

	root 'games#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/game.rb
class Game < ApplicationRecord
	validates :title, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
	
	def index
		@games = Game.all
	end

	def show
		@game = Game.find(params[:id])
	end

	def new
		@game = Game.new
	end

	def create
		@games = Game.all
		@game = Game.create(game_params)
	end

	def edit
		@game = Game.find(params[:id])
	end

	def update
		@games = Game.all
		@game = Game.find(params[:id])

		@game.update_attributes(game_params)
	end

	def delete
		@game = Game.find(params[:game_id])
	end

	def destroy
		@games = Game.all
		@game = Game.find(params[:id])
		@game.destroy
	end

	private
		def game_params
			params.require(:game).permit(:title, :description, :genre)
		end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/games_helper.rb
module GamesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/games/_delete.html.erb
<div class="modal-dialog">
  <div class="modal-content">
  <div class="modal-header">
    <h3>Delete Game</h3>
  </div>
  <div class="modal-body">
  <ul class="errors"></ul>
  Are you sure you wish to delete <b><%= @game.title %></b>?
  </div>
  <div class="modal-footer">
    <%= link_to "Yes, Delete This Game", game_path(@game), method: :delete, remote: true, class: "btn btn-danger" %>
    <%= link_to "No, Please Don't", "#", class: "btn btn-default", data: { dismiss: "modal" } %>
  </div>
  </div>
</div>

app/views/games/_edit.html.erb
<div class="modal-header">
	<h1>Editing "<%= @game.title %>"</h1>
</div>
<%= render 'form' %>

app/views/games/_form.html.erb
<div class="modal-dialog">
	<div class="modal-content">
		<%= form_for @game, remote:true do |f| %>
		<div class="modal-body">
			<%= hidden_field_tag :authenticity_token, form_authenticity_token %>
			<!-- Checks for any errors -->
			<ul class="errors"></ul>
			 
			<!-- group for the title field of form -->
			<div class="form-group">
				<%= f.label :title %><br>
				<%= f.text_field :title %>
			</div>
		 
			<!-- group for the description field of form -->
		    <div class="form-group">
		    	<%= f.label :description %><br>
		    	<%= f.text_area :description %>
		    </div>
		    
			<!-- group for radio buttons to choose genre -->
			<div class="form-group">
				<%= f.radio_button(:genre, "Shooter") %>
				<%= label_tag(:genre_shooter, "Shooter") %>
				<%= f.radio_button(:genre, "Puzzle") %>
				<%= label_tag(:genre_puzzle, "Puzzle")%>
				<%= f.radio_button(:genre, "CCG") %>
			    <%= label_tag(:genre_ccg, "CCG")%>
			    <%= f.radio_button(:genre, "MOBA") %>
			    <%= label_tag(:genre_moba, "MOBA")%>
			    <%= f.radio_button(:genre, "RPG") %>
			    <%= label_tag(:genre_rpg, "RPG")%>
			    <%= f.radio_button(:genre, "Fitness") %>
			    <%= label_tag(:genre_fitness, "Fitness")%>
			</div> 
			
		</div> <!-- end of modal-body -->
		<div class="modal-footer">
		    <%= f.submit class: "btn btn-primary"%>
			<%= link_to "Cancel", "#", class: "btn", data: {dismiss: "modal"} %>
		</div> <!-- closing modal-footer -->
		<% end %> <!-- end of form -->
	</div> <!-- closing modal-content -->
</div> <!-- closing modal-dialog -->

app/views/games/_index.html.erb
<% @games.each do |game| %>
	<tr>
		<td><%= link_to game.title, game_path(game) %></td>
		<td><%= game.description %></td>
		<td><%= game.genre %></td>
		<td><%= link_to 'Edit', edit_game_path(game), remote: true, class: "btn btn-default" %></td>
		<td><%= link_to "Delete", game_delete_path(game), remote: true, class: "btn btn-danger"%></td>
	</tr>
<% end %>

app/views/games/_new.html.erb
<div class="modal-header">
	<h1>New Game</h1>
</div>
<%= render 'form' %>

app/views/games/_save.js.erb
$("ul.errors").html("")
<% if @game.errors.any? %>
  <% @game.errors.full_messages.each do |message| %>
    $("ul.errors").append($("<li />").html("<%= message.html_safe %>"))
  <% end %>
<% else %>
  $(".game-index").html("<%= j render('index') %>")
  $("#game-modal").modal("hide")
<% end %>

app/views/games/create.js.erb
<%= render "save" %>

app/views/games/delete.js.erb
$("#game-modal").html("<%= escape_javascript(render 'delete') %>")
$("#game-modal").modal("show")

app/views/games/destroy.js.erb
<%= render "save" %>

app/views/games/edit.js.erb
$("#game-modal").html("<%= j render('edit') %>");
$("#game-modal").modal("show")

app/views/games/index.html.erb
<h1>Games!</h1>
 
<%= link_to 'New Game Entry', new_game_path, remote: true, class: "btn btn-primary"%><br>

  <% if @games.any? %>
	<table class="table table-bordered table-striped">
	 <tr>
	    <th>Title</th>
	    <th>Description</th>
	    <th>Genre</th>
	 </tr>
	 
	 <tbody class="game-index">
	 	<%= render "index" %>
	 </tbody>

	</table>
  <% else %>
	<h2>Looks like there's no games here!<br>
	Make a new one!
	</h2>
  <% end %>

<div id="game-modal" class="modal fade"></div>

app/views/games/new.js.erb
$("#game-modal").html("<%= escape_javascript(render 'new') %>")
$("#game-modal").modal("show")

app/views/games/show.html.erb
<p><strong>Title: </strong><br><%= @game.title %></p>
<p><strong>Description: </strong><br><%= @game.description%></p>
<p><strong>Genre: </strong><br><%= @game.genre %></p>

<%= link_to 'Return to List', games_path, class: "btn btn-default" %> 
<%= link_to 'Edit', edit_game_path, remote: true, class: "btn btn-primary" %><br>

app/views/games/update.js.erb
<%= render "save" %>

app/views/home/index.html.erb
<h2>Home page!</h2>

<%= link_to 'Games list!', controller: 'games' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blag</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>